Algoritmo "exercicio9"

Var
nome, sexo: caracter
idade, cont: inteiro

Inicio

para cont de 1 ate 20 passo 1 faca
   escreval("Escreva seu nome inteiro: ")
   leia(nome)

   escreval("Escreva seu genero (Masculino ou Feminino): ")
   leia(sexo)

   escreval("Escreva sua idade: ")
   leia(idade)

   se sexo = "Masculino" entao
      se idade >= 21 entao
         escreval(nome)
      fimse
   fimse
fimpara


Fimalgoritmo